# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

pom_version=0.0.4-1.20.1
mc_version=1.20.1
forge_version=1.20.1-47.3.0
forgegradle_version=6.0.+
mixin_version=0.8.5
parchment_version=2023.09.03

jei_version=15.20.0.106
jei_mc_version=1.20.1
citadel_version=6002521
ferritecore_version=4810975

mixingradle_version = 0.7-SNAPSHOT