modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="pixelsofmc"
version="0.0.4-1.19.3"
displayName="The Pixels of Minecraft"
credits="Special thanks to KaupenJoe (https://www.youtube.com/c/TKaupenjoe) and his awesome community, without them I would not have been able to make this mod. \nSome parts of this mod make use of code from other mods, the details can be found in the CREDITS.txt on github."
displayURL=""
authors="Turtle-Master42"
description='''
WIP
'''

[[dependencies.pixelsofmc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3]"
    ordering="NONE"
    side="BOTH"


[modproperties.pixelsofmc]
configuredBackground="minecraft:textures/block/ancient_debris.png"



